[package]
name = "modbus-test"
version = "0.1.0"
authors = ["Michał Hanusek <mhanusek@energotest.com.pl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libmodbus-rs = "*"
